In [1]:
import numpy as np
from npknn import NonparametricKNN

In [2]:
#Data
train = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
target = np.array([1,2,3,7,17])
test = np.array([[3,3,3],[6,6,6]])

In [3]:
#Initialize model
model = NonparametricKNN(n_neighbors=3,loss='L2')
#Train
model.fit(train,target)
#Predict
model.predict(test)

array([ 4.,  9.])

In [4]:
#When we use L2 loss, we get exactly the same result as the KNN regressor in sklearn.
from sklearn.neighbors import KNeighborsRegressor
model = NonparametricKNN(n_neighbors=3)
model.fit(train,target)
model.predict(test)

array([ 4.,  9.])

In [5]:
#When we use other loss, predictions could be different.
model = NonparametricKNN(n_neighbors=3,loss='L1')
model.fit(train,target)
model.predict(test)

array([3, 7])

In [6]:
#Customized loss
def loss(pred,true):#Loss function should take two numpy arrays as inputs...
    result = np.power(pred-true,4)
    return result.mean()#and return a scalar.
model = NonparametricKNN(n_neighbors=3,loss=loss)#Pass the loss function as argument.
model.fit(train,target)
model.predict(test)

array([ 4.,  9.])